version: "3.7"

services:
  upscaling:
    build: .
    container_name: SwinIR
    volumes:
      - ./data:/SwinIR/data
    
    # runtime: nvidia
    # OR
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    #           driver: nvidia