version: "3.7"

services:
  upscaling:
    build: .
    container_name: SwinIR
    restart: always
    volumes:
      - ./data:/data:rw
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  # test:
  #   image: tensorflow/tensorflow:latest-gpu
  #   command: python -c "import tensorflow as tf;tf.test.gpu_device_name()"
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #         - driver: nvidia
  #           device_ids: ['0']
  #           capabilities: [gpu]